name: Deploy Node Application

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Login to docker hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build -t anshumant72/varsha-mekup-studio-frontend .
    - name: Publish the Docker image to Docker Hub
      run: docker push anshumant72/varsha-mekup-studio-frontend:latest
  
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull anshumant72/varsha-mekup-studio-frontend:latest
      - name: Delete the old Container
        run: docker rm -f varsha-mekup-studio-fronend
      - name: Run the Docker container
        run: docker run -d -p 4000:4000 --name varsha-mekup-studio-frontend anshumant72/varsha-mekup-studio-frontend:latest

